on:
  workflow_call:
    inputs:
      aws_role_arn:
        required: true
        type: string
      aws_region:
        required: false
        type: string
      ecr_url:
        required: true
        type: string

jobs:
  build:
    name: Build Image
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install Packages
      run: | 
        sudo apt update -y && \
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
        unzip awscliv2.zip && \
        sudo ./aws/install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
        role-duration-seconds: 1800
    
    - name: Generate Short SHA
      id: sha8
      shell: bash
      run: echo ::set-output name=SHA8::$(echo $GITHUB_SHA | cut -c1-8)

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        pull: true
        push: true
        tags: |
          "${{ env.ECR_URL }}:${{ steps.sha8.outputs.SHA8 }}"
        cache-from: type=gha
        cache-to: type=gha,mode=max
